# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='enrollment',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
