# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateapp', '0003_course_courserating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(default=0),
        ),
    ]
